# Generated by Django 5.1.7 on 2025-03-16 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_is_featured_event_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('interests', models.CharField(blank=True, max_length=255)),
                ('is_student', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
