# Generated by Django 5.1.7 on 2025-03-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_incomingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingemail',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='extracted_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
