# Generated by Django 5.1.7 on 2025-03-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_incomingemail_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingemail',
            name='extracted_links',
        ),
    ]
