# Generated by Django 5.1.7 on 2025-03-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_options_rename_image_event_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_published',
            new_name='is_active',
        ),
    ]
