# Generated by Django 5.1.7 on 2025-03-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_description_user_graduating_year_user_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Whether this user should be displayed on the main page'),
        ),
    ]
